name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://server-anda/deploy.php
          method: POST
